[package]
name = "smtp2s"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "json", "registry"] }
